version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /code/entrypoint.sh
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db