# Generated by Django 2.2 on 2019-04-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=3)),
                ('to', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ('currency_id',),
                'unique_together': {('domain', 'to')},
            },
        ),
    ]
