# Generated by Django 2.2 on 2019-04-17 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='to',
            new_name='codomain',
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('domain', 'codomain')},
        ),
    ]
