# Generated by Django 2.2 on 2019-04-17 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20190417_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('currency_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField()),
                ('date', models.BigIntegerField()),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
            ],
            options={
                'ordering': ('currency_id', 'date'),
                'unique_together': {('currency_id', 'date')},
            },
        ),
    ]
