# Generated by Django 2.2 on 2019-04-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_currencyrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='currency_id',
            field=models.ForeignKey(db_column='currency_id', on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency'),
        ),
    ]
